apiVersion: v2
name: pkgsite
description: A Helm chart for Kubernetes

type: application

version: 0.4.0

appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 13.1.5
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: redis
    version: 18.1.6
    condition: redis.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: athens-proxy
    repository: https://gomods.github.io/athens-charts
    version: 0.7.1
    condition: athens-proxy.enabled
